spring:
  profiles:
    active: test
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://192.168.2.11:3306/chinamall_multisite?useUnicode=true&characterEncoding=utf8
server:
    port: 8080
    compression:
      enabled: true
      mime-types: text/html,text/xml,text/plain,text/css, application/javascript, application/json
  session:
    timeout: 10000