spring:
  profiles:
    active: dev
  application:
    name: demo
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.2.11:3306/chinamall_multisite?useUnicode=true&characterEncoding=utf8
    name:
    username: erp
    password: 123456
server:
  port: 10070