spring:
  profiles:
    active: dev
  application:
    name: demo
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.2.88:3306/db1?useUnicode=true&characterEncoding=utf8
    name:
    username: root
    password: 123456
server:
  port: 10070